### ISSUE TITLE
Check the files size before downloading

### ISSUE THREAD

**Issue by clarriu97** [clarriu97/virus-total-telegram-bot#1]
## Current behaviour

The current flow is this one:

1. The user sends a file
2. The bot downloads the file in the server
3. Check audio size
4. If the size is bigger than the limit, return and send an informative error message to the user

## Potential problem

If a malicious user like `gbar` wants to destroy your server could send very big files and collapse the memory of the system.

## Desired behaviour

The desired flow would be:

1. The user sends a file
2. The bot checks the size before downloading
3. If the size of bigger than the limit, return and send an informative error message to the user.
4. Otherwise, download the file and continue.

## Tasks

- [x] Explore the options given by `python-telegram-bot`
- [x] Code the solution
- [x] Test that the solution works

## References

- [Stackoverflow question](https://stackoverflow.com/questions/67583219/telethon-get-media-size-before-download)
