### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by clarriu97** [clarriu97/virus-total-telegram-bot#2]
## Context

This is a python app which will be released, and the standard way nowadays is using docker.

## Goal

Create a functional Dockerfile that creates the application Docker

## Tasks

- [ ] Create a cythonized wheel
- [ ] Install dependencies and wheel
- [ ] Base on ubuntu:20.04
- [ ] Tini entrypoint
